
/**
 * A long-form cinematic letter for Esther (Ademide)
 * From Inioluwa (Sojourner)
 */
type LineInfo = {
  text: string;
  pause: number;
};

export const lines: LineInfo[] = [
  { text: "In all honesty...", pause: 1000 },
  { text: "I do not easily get mushy mushy.", pause: 1500 },
  { text: "I usually keep my guards up, my thoughts locked away in some shadowed corner of my mind.", pause: 1200 },
  { text: "But with you, something shifts—I'm ready to pour it all out, though I'm not entirely sure why.", pause: 1800 },
  { text: "I’m ready to say all that burdens me, not just because you listen...", pause: 2000 },
  { text: "But because Inioluwa feels your presence and symphony, in ways that defy simple explanation.", pause: 2200 },
  { text: "It’s funny—or perhaps peculiar—how my world has tilted since you entered it.", pause: 1500 },
  { text: "I find myself planning my entire day around you, or at least trying to.", pause: 1800 },
  { text: "Because I cherish every moment—every text, every call, every fleeting second that might hold a hidden meaning.", pause: 2000 },
  { text: "Just holding your hands and staring right at the beautiful soul within, wondering what secrets it holds...", pause: 2500 },
  { text: "In the time I've spent knowing you, my heart has finally found its peace close to yours....", pause: 2200 },
  { text: "I can feel your voice and its soothing tempo in my bones, echoing like a distant melody.", pause: 1800 },
  { text: "(Sometimes I can even feel the strings tugging at my heart when we don’t talk, pulling me toward unknowns).", pause: 2500 },
  { text: "Ademide, I want to be with you, come rain or shine—or whatever storms may brew.", pause: 2000 },
  { text: "You’ve changed my perspective on so many things, some I didn't even realize needed changing.", pause: 1500 },
  { text: "You’ve become my Aurora Borealis—a light I never expected but now can't live without, though its glow sometimes flickers mysteriously.", pause: 2500 },
  { text: "The way you make me feel safe enough to be myself...", pause: 1800 },
  { text: "That soothing warmth? It’s something I’ve hardly ever experienced before, and it leaves me questioning its origins.", pause: 2200 },
  { text: "I don't want to imagine my days without you in them anymore, but sometimes shadows of doubt creep in.", pause: 2000 },
  { text: "So I’m asking: would you be willing to take this journey with me?", pause: 2500 },
  { text: "To explore everything we could be together, navigating the ambiguities along the way?", pause: 1500 },
  { text: "I know it’s scary to be this open, but my heart won't let me hide it anymore, even if parts remain veiled.", pause: 2200 },
  { text: "You are worth the risk. You are worth every single leap of faith, no matter the uncertain landing.", pause: 2500 },
  { text: "And your smile...", pause: 1500 },
  { text: "God, that smile always brightens up my day, or at least casts a curious light on it.", pause: 1800 },
  { text: "It’s the reason I’ve been asking for so many video calls lately, hoping to unravel its enigma.", pause: 1500 },
  { text: "Your smile anchors me. It is one of the most majestic things I know, yet it hints at untold stories.", pause: 2200 },
  { text: "The quiet proof that in this restless world, there is always a place called home—or perhaps just the illusion of one.", pause: 2500 },
  { text: "I've seen many beautiful sights, but nothing like the way your smile breaks the silence, leaving echoes of wonder.", pause: 2200 },
  { text: "It is a sudden dawn, an infusion of pure joy into my heart, mixed with a touch of melancholy.", pause: 2000 },
  { text: "A radiant light that humbles the stars and aligns my world again, though alignments can shift.", pause: 2500 },
  { text: "To be the reason behind that smile makes me the happiest man alive, or so I believe in these moments.", pause: 2200 },
  { text: "As a 'Sojourner' on this journey, your smile is one of my  guides, leading through fog and clarity alike.", pause: 2000 },
  { text: "It’s not harsh, it’s not judgmental—it is 'EWA' in its purest form, or maybe a deeper essence.", pause: 2500 },
  { text: "It turns my struggles and my 'push' into honor, transforming the ordinary into something profound yet ambiguous.", pause: 2000 },
  { text: "It makes me feel like a King in my own right, reigning over realms both seen and unseen.", pause: 1800 },
  { text: "Esther, even on the most uncertain days, it feels like the heavens nod in agreement—or perhaps whisper secrets.", pause: 2500 },
  { text: "You are my beautiful destination, though the path there winds in unexpected ways.", pause: 2000 },
  { text: "The first stop before we continue this journey hand in hand, exploring the unknowns together.", pause: 2200 },
  { text: "(Maybe even with some cute, Godly kids running around later, if fate aligns 🌚).", pause: 2500 },
  { text: "To see you smile is to see beauty find its purpose, or perhaps redefine it entirely.", pause: 2000 },
  { text: "You are a gem that makes every mile worth taking... orente mi, with all your hidden facets.", pause: 2500 },
  { text: "In this world of constant noise and moving pixels...", pause: 1800 },
  { text: "In my little world of meetings and code, you are the steady rhythm, interrupting the chaos subtly.", pause: 2200 },
  { text: "A grace that makes me turn every normal thing into something sacred, or at least spiritually intriguing.", pause: 2500 },
  { text: "I appreciate you. I love you. I respect you.", pause: 1800 },
  { text: "More than time, and certainly more than the distance between us, which sometimes feels eternal.", pause: 2500 },
  { text: "I am yours—unconditionally and irrevocably, though life may test that vow.", pause: 2200 },
  { text: "I want to start and end every single day with you.", pause: 2000 },
  { text: "I wouldn't have it any other way, despite the whispers of alternatives.", pause: 1500 },
  { text: "I love us. I love being the one you call 'Oba'.", pause: 2200 },
  { text: "I still think back to when it all started...", pause: 1500 },
  { text: "Finding excuses to see you, the long texts, watching 'Suits' together...", pause: 2200 },
  { text: "I’m so happy for that period. It led me to you, through twists I couldn't foresee.", pause: 2000 },
  { text: "I pray that we protect the core of what makes us love each other, guarding against unseen erosions.", pause: 2500 },
  { text: "Until the day people look at us and say...", pause: 1800 },
  { text: "‘Damnn... they actually married each other like they said.’", pause: 3500 },
  { text: "", pause: 500 },
  { text: "But let's rewind a bit, to those early days in KADUNA.", pause: 2000 },
  { text: "The simple moments that built this foundation, layered with unspoken understandings.", pause: 2200 },
  { text: "From small beginnings to these big dreams in Lagos, where ambitions blur with realities.", pause: 2000 },
  { text: "Even when things got tough—like when my laptop literally smoked out...", pause: 2200 },
  { text: "You were one steady factor that didn't glitch, or at least appeared unbreakable.", pause: 2000 },
  { text: "In those chaotic times, your presence was a quiet anchor amid the storm.", pause: 2500 },
  { text: "I remember the nights we'd talk about the future, painting pictures with vague strokes.", pause: 2000 },
  { text: "It seemed so far away then, didn't it? Like a distant horizon we chased.", pause: 1800 },
  { text: "But now, every line of code I write is for us, embedding our story in digital threads.", pause: 2200 },
  { text: "Every late night at the office is a step closer to you, though the path isn't always straight.", pause: 2000 },
  { text: "I want to build a life where 'long distance' is just a memory, faded like old code.", pause: 2500 },
  { text: "Where the only thing between us is the morning coffee, shared in silent companionship.", pause: 2000 },
  { text: "I can see us in our own home, laughing about these days, reminiscing with a touch of nostalgia.", pause: 2200 },
  { text: "I can see the Godly, beautiful kids we talked about, bringing new ambiguities to our lives.", pause: 2000 },
  { text: "Their laughter echoing through rooms we've yet to build.", pause: 2200 },
  { text: "I want to be the man who supports your every dream, even the ones you haven't voiced yet.", pause: 2200 },
  { text: "The one who cheers loudest for every one of your wins, celebrating the victories and the near-misses.", pause: 2000 },
  { text: "Because your happiness is my greatest project, an ongoing endeavor with no clear end.", pause: 2500 },
  { text: "You are the masterpiece I get to witness every day, evolving in ways I can't predict.", pause: 2200 },
  { text: "I promise to stay vulnerable with you, even when it's hard and the words falter.", pause: 2000 },
  { text: "I promise to protect this 'core' we’ve built so carefully, shielding it from external ambiguities.", pause: 2200 },
  { text: "I promise to keep choosing you, day after day, through clarity and confusion.", pause: 2000 },
  { text: "Through the bugs, the crashes, and the triumphs that define our shared journey.", pause: 1800 },
  { text: "You are my favorite person to talk to, Esther, unraveling thoughts I didn't know I had.", pause: 2200 },
  { text: "My favorite person to dream with, weaving futures from threads of possibility.", pause: 2000 },
  { text: "My favorite person to love, in all its beautiful, ambiguous glory.", pause: 2500 },
  { text: "I pray that God keeps us and guards our hearts, guiding us through the uncertainties.", pause: 2200 },
  { text: "Until the day the distance is finally zero, and proximity brings new mysteries.", pause: 2500 },
  { text: "Until the day the promises become reality, or evolve into something even greater.", pause: 2200 },
  { text: "Until the day the world looks at us and sees the grace we've cultivated.", pause: 2000 },
  { text: "Until they say...", pause: 1500 },
  { text: "‘Damnn... they actually married each other like they said.’", pause: 3500 },
  { text: "I love you so much, Ade mi.", pause: 2000 },
  { text: "You are my beginning and —or perhaps the endless loop in between.", pause: 2200 },
  { text: "Always yours, Inioluwa.", pause: 2500 },
  { text: "", pause: 1000 },
  { text: "P.S. In the quiet hours, I wonder what other layers we'll discover in each other...", pause: 2500 },
  { text: "Layers that add depth to this journey, making it all the more intriguing.", pause: 2200 },
  { text: "Until then, hold onto my words—they make the certainties shine brighter.", pause: 3000 },
  { text: "And the ambiguities... well, they just make the story richer, don't they?", pause: 2500 },
  { text: "I can't wait to see where this journey takes us, hand in hand, heart to heart.", pause: 2500 },
   { text: "With all my love, Inioluwa.", pause: 2000 },
   {text: "P.P.S. I hope this letter finds you in a moment of calm, where you can feel the sincerity behind every word.", pause: 2500 },
   { text: "And if it brings a smile to your face, know that it's the same smile that lights up my world every time I think of you.", pause: 2500 },
   { text: "I love you, Esther. More than words can capture, more than time can measure.", pause: 3000 },
   {
      text: "I am so grateful for you, for us, and for the beautiful journey we're on together.", pause: 2500
   },
{text: "Until the day we can finally say 'I do' in front of everyone, and maybe even in front of God, if He allows us that honor.", pause: 2500 },
{ text: "I look forward to every moment with you, from the mundane to the extraordinary, because with you, everything feels extraordinary.", pause: 2500 },
{ text: "I want to be the one who stands by your side through every chapter of our story, writing it together with love and laughter.", pause: 2500 },
{ text: "I want to be the one who holds your hand through every challenge, celebrating every victory, and cherishing every moment in between.", pause: 2500 },
{ text: "I want to be the one who loves you unconditionally, through every twist and turn, through every high and low.", pause: 2500 },
{ text: "I want to be the one who makes you feel safe, cherished, and adored, every single day of our lives.", pause: 2500 },
{ text: "I want to be the one who grows with you, learns with you, and builds a future with you that is filled with love and happiness.", pause: 2500 },
{ text: "I want to be the one who stands by your side through every chapter of our story, writing it together with love and laughter.", pause: 2500 },
{text: "with all my love, Oba.", pause: 2000 },
{ text: "P.P.P.S. I hope this letter serves as a reminder of how deeply I care for you, and how excited I am for the future we will build together.", pause: 2500 },
{text:"💖💘💝💟 ", pause: 3000 },
];